name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Restore node_modules from cache
        uses: actions/cache/restore@v4
        id: bun-restore-cache
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Run TypeScript check
        run: bun tsc

      - name: Run ESLint
        run: bun lint

      - name: Save Bun Cache
        id: cache-bun-save
        uses: actions/cache/save@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ steps.bun-restore-cache.outputs.cache-primary-key }}
